# README.md generation configuration file

# Title configuration
title:
  main: "👋 Hello World! NeatGuy is Coding~"

# Dynamic typing effect configuration
typing_svg:
  font: "Fira+Code"
  pause: 1000
  color: "36BCF7"
  center: true
  vCenter: true
  width: 635
  lines:
    - "Passionate+Technology+Leader+and+Developer"
    - "Always+Learning+and+Challenging"

# About Me section configuration
about_me:
  title: "💫 About Me"
  items:
    - icon: "🔭"
      text: "Driving innovative projects forward as a Technology Leader"
    - icon: "🌱"
      text: "Continuously expanding my expertise through emerging technologies and embracing new challenges"
    - icon: "💬"
      text: "Open to discussions on all tech-related topics—feel free to reach out"

# Tech Stack section configuration
tech_stack:
  title: "🛠️ Tech Stack"
  categories:
    - name: "Programming Languages"
      technologies:
        - name: "Java"
          color: "007396"
          logo: "java"
          logoColor: "white"
        - name: "C++"
          color: "00599C"
          logo: "cplusplus"
          logoColor: "white"
        - name: "Python"
          color: "3776AB"
          logo: "python"
          logoColor: "white"
        - name: "Go"
          color: "00ADD8"
          logo: "go"
          logoColor: "white"
        - name: "Rust"
          color: "000000"
          logo: "rust"
          logoColor: "white"
        - name: "JavaScript"
          color: "F7DF1E"
          logo: "javascript"
          logoColor: "black"
        - name: "TypeScript"
          color: "3178C6"
          logo: "typescript"
          logoColor: "white"
        - name: "Ruby"
          color: "CC342D"
          logo: "ruby"
          logoColor: "white"
        - name: "PHP"
          color: "777BB4"
          logo: "php"
          logoColor: "white"
        - name: "Kotlin"
          color: "0095D5"
          logo: "kotlin"
          logoColor: "white"
        - name: "Swift"
          color: "FA7343"
          logo: "swift"
          logoColor: "white"
        - name: "Scala"
          color: "DC322F"
          logo: "scala"
          logoColor: "white"
    - name: "Row-based Databases"
      technologies:
        - name: "MySQL"
          color: "4479A1"
          logo: "mysql"
          logoColor: "white"
        - name: "Oracle"
          color: "F80000"
          logo: "oracle"
          logoColor: "white"
        - name: "PostgreSQL"
          color: "336791"
          logo: "postgresql"
          logoColor: "white"
        - name: "DynamoDB"
          color: "4053D6"
          logo: "amazon-dynamodb"
          logoColor: "white"
        - name: "MariaDB"
          color: "003545"
          logo: "mariadb"
          logoColor: "white"
        - name: "SQLite"
          color: "003B57"
          logo: "sqlite"
          logoColor: "white"
    - name: "Column-based Databases"
      technologies:
        - name: "HBase"
          color: "D22128"
          logo: "apache"
          logoColor: "white"
        - name: "ClickHouse"
          color: "FFCC01"
          logo: "clickhouse"
          logoColor: "black"
        - name: "Bigtable"
          color: "4285F4"
          logo: "google-cloud"
          logoColor: "white"
    - name: "Graph Databases"
      technologies:
        - name: "Neo4J"
          color: "008CC1"
          logo: "neo4j"
          logoColor: "white"
    - name: "Search Engines"
      technologies:
        - name: "ElasticSearch"
          color: "005571"
          logo: "elasticsearch"
          logoColor: "white"
        - name: "Solr"
          color: "D9411E"
          logo: "apache-solr"
          logoColor: "white"
        - name: "Lucene"
          color: "D9411F"
          logo: "apache-lucene"
          logoColor: "black"
    - name: "Cache & NoSQL"
      technologies:
        - name: "Redis"
          color: "DC382D"
          logo: "redis"
          logoColor: "white"
        - name: "Cassandra"
          color: "1287B1"
          logo: "apache-cassandra"
          logoColor: "white"
        - name: "Memcached"
          color: "005571"
          logo: "memcached"
          logoColor: "white"
    - name: "Data Lake & Warehouse"
      technologies:
        - name: "Hive"
          color: "FDEE21"
          logo: "apache-hive"
          logoColor: "black"
        - name: "Doris"
          color: "00BFFF"
          logo: "apache"
          logoColor: "white"
        - name: "Starrocks"
          color: "0078D4"
          logo: "starrocks"
          logoColor: "white"
        - name: "Druid"
          color: "29F1FB"
          logo: "apache-druid"
          logoColor: "black"
        - name: "Pinot"
          color: "E95420"
          logo: "apache"
          logoColor: "white"
        - name: "Snowflake"
          color: "29B5E8"
          logo: "snowflake"
          logoColor: "white"
        - name: "BigQuery"
          color: "4285F4"
          logo: "google-cloud"
          logoColor: "white"
    - name: "Vector Databases"
      technologies:
        - name: "Pinecone"
          color: "000000"
          logo: "pinecone"
          logoColor: "white"
        - name: "Qdrant"
          color: "5A29E4"
          logo: "qdrant"
          logoColor: "white"
        - name: "Weaviate"
          color: "3F51B5"
          logo: "weaviate"
          logoColor: "white"
        - name: "Milvus"
          color: "45B8AC"
          logo: "milvus"
          logoColor: "white"
    - name: "Message Queues"
      technologies:
        - name: "RocketMQ"
          color: "D77310"
          logo: "apache-rocketmq"
          logoColor: "white"
        - name: "Kafka"
          color: "231F20"
          logo: "apache-kafka"
          logoColor: "white"
        - name: "Pulsar"
          color: "188FFF"
          logo: "apache-pulsar"
          logoColor: "white"
        - name: "RabbitMQ"
          color: "FF6600"
          logo: "rabbitmq"
          logoColor: "white"
        - name: "ActiveMQ"
          color: "EF2D56"
          logo: "apache"
          logoColor: "white"
    - name: "DevOps"
      technologies:
        - name: "Kubernetes"
          color: "326CE5"
          logo: "kubernetes"
          logoColor: "white"
        - name: "Helm"
          color: "0F1689"
          logo: "helm"
          logoColor: "white"
        - name: "ArgoCD"
          color: "EF7B4D"
          logo: "argo"
          logoColor: "white"
        - name: "Jenkins"
          color: "D24939"
          logo: "jenkins"
          logoColor: "white"
        - name: "GitLab"
          color: "FCA121"
          logo: "gitlab"
          logoColor: "white"
        - name: "GitHub"
          color: "181717"
          logo: "github"
          logoColor: "white"
        - name: "Terraform"
          color: "623CE4"
          logo: "terraform"
          logoColor: "white"
        - name: "Ansible"
          color: "EE0000"
          logo: "ansible"
          logoColor: "white"
    - name: "Cloud Services"
      technologies:
        - name: "AWS"
          color: "232F3E"
          logo: "amazon-aws"
          logoColor: "white"
        - name: "Route53"
          color: "8C4FFF"
          logo: "amazon-aws"
          logoColor: "white"
        - name: "ALB/ELB"
          color: "FF9900"
          logo: "amazon-aws"
          logoColor: "white"
        - name: "S3"
          color: "569A31"
          logo: "amazon-s3"
          logoColor: "white"
        - name: "EC2"
          color: "FF9900"
          logo: "amazon-ec2"
          logoColor: "white"
        - name: "RDS"
          color: "527FFF"
          logo: "amazon-aws"
          logoColor: "white"
        - name: "SageMaker"
          color: "FF9900"
          logo: "amazon-aws"
          logoColor: "white"
        - name: "GCP"
          color: "4285F4"
          logo: "google-cloud"
          logoColor: "white"
        - name: "Azure"
          color: "0078D4"
          logo: "microsoft-azure"
          logoColor: "white"
    - name: "Java Frameworks"
      technologies:
        - name: "Spring"
          color: "6DB33F"
          logo: "spring"
          logoColor: "white"
        - name: "Spring Boot"
          color: "6DB33F"
          logo: "spring-boot"
          logoColor: "white"
        - name: "Spring Cloud"
          color: "6DB33F"
          logo: "spring"
          logoColor: "white"
        - name: "Quarkus"
          color: "4695EB"
          logo: "quarkus"
          logoColor: "white"
        - name: "MyBatis"
          color: "000000"
          logo: "mybatis"
          logoColor: "white"
        - name: "Netty"
          color: "2C2D72"
          logo: "netty"
          logoColor: "white"
        - name: "Hibernate"
          color: "59666C"
          logo: "hibernate"
          logoColor: "white"
    - name: "Python Frameworks"
      technologies:
        - name: "Celery"
          color: "37814A"
          logo: "celery"
          logoColor: "white"
        - name: "SQLAlchemy"
          color: "D71F00"
          logo: "sqlalchemy"
          logoColor: "white"
        - name: "Pydantic"
          color: "E92063"
          logo: "pydantic"
          logoColor: "white"
        - name: "NumPy"
          color: "013243"
          logo: "numpy"
          logoColor: "white"
        - name: "SciPy"
          color: "8CAAE6"
          logo: "scipy"
          logoColor: "white"
        - name: "Keras"
          color: "D00000"
          logo: "keras"
          logoColor: "white"
        - name: "Flask"
          color: "F12345"
          logo: "flask"
          logoColor: "white"
        - name: "Django"
          color: "AC1289"
          logo: "django"
          logoColor: "white"
        - name: "FastAPI"
          color: "009688"
          logo: "fastapi"
          logoColor: "white"
    - name: "Go Frameworks"
      technologies:
        - name: "Gin"
          color: "00ADD8"
          logo: "go"
          logoColor: "white"
        - name: "Kratos"
          color: "00ADD8"
          logo: "go"
          logoColor: "white"
        - name: "SQLX"
          color: "00ADD8"
          logo: "go"
          logoColor: "white"
        - name: "Cobra"
          color: "00ADD8"
          logo: "go"
          logoColor: "white"
        - name: "Testify"
          color: "00ADD8"
          logo: "go"
          logoColor: "white"
        - name: "Echo"
          color: "00ADD8"
          logo: "go"
          logoColor: "white"
    - name: "Frontend Frameworks"
      technologies:
        - name: "Next.js"
          color: "000000"
          logo: "next.js"
          logoColor: "white"
        - name: "React"
          color: "61DAFB"
          logo: "react"
          logoColor: "black"
        - name: "TailwindCSS"
          color: "38B2AC"
          logo: "tailwind-css"
          logoColor: "white"
        - name: "HeadlessUI"
          color: "66E3FF"
          logo: "headlessui"
          logoColor: "black"
        - name: "Lexical"
          color: "61DAFB"
          logo: "react"
          logoColor: "black"
        - name: "Vue.js"
          color: "4FC08D"
          logo: "vue.js"
          logoColor: "white"
        - name: "Angular"
          color: "DD0031"
          logo: "angular"
          logoColor: "white"
        - name: "Svelte"
          color: "FF3E00"
          logo: "svelte"
          logoColor: "white"

# Repository Contributions section configuration
repository_contributions:
  title: "👨‍💻 Repository Contributions"
  username: "NeatGuyCoding"
  repositories:
    - name: "Dify"
      owner: "langgenius"
      repo_name: "dify"
      description: "Dify is an open-source LLM app development platform. Dify's intuitive interface combines AI workflow, RAG pipeline, agent capabilities, model management, observability features and more, letting you quickly go from prototype to production."
      technologies:
        - name: "Python"
          color: "3776AB"
          logo: "python"
          logoColor: "white"
        - name: "JavaScript"
          color: "F7DF1E"
          logo: "javascript"
          logoColor: "black"
        - name: "TypeScript"
          color: "3178C6"
          logo: "typescript"
          logoColor: "white"
      contribution_type: "issues"
    - name: "Dify-plugin-daemon"
      owner: "langgenius"
      repo_name: "dify-plugin-daemon"
      description: "Dify Plugin Daemon is a service that manages the lifecycle of plugins."
      technologies:
        - name: "Go"
          color: "00ADD8"
          logo: "go"
          logoColor: "white"
      contribution_type: "issues"
    - name: "langchain4j"
      owner: "langchain4j"
      repo_name: "langchain4j"
      description: "Java version of LangChain"
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "issues"
    - name: "Spring Framework"
      owner: "spring-projects"
      repo_name: "spring-framework"
      description: "https://spring.io/projects/spring-framework"
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "issues"
    - name: "Mycat-Server"
      owner: "MyCATApache"
      repo_name: "Mycat-Server"
      description: "A comprehensive solution for sharding database data"
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "issues"
    - name: "JFR-Unit"
      owner: "moditect"
      repo_name: "jfrunit"
      description: "A JUnit extension for asserting JDK Flight Recorder events"
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "commits"
    - name: "OpenJDK"
      owner: "openjdk"
      repo_name: "jdk"
      description: "JDK main-line development https://openjdk.org/projects/jdk"
      technologies:
        - name: "C++"
          color: "00599C"
          logo: "cplusplus"
          logoColor: "white"
      contribution_type: "issues"
    - name: "bookkeeper"
      owner: "apache"
      repo_name: "bookkeeper"
      description: "Apache BookKeeper - a scalable, fault tolerant and low latency storage service optimized for append-only workloads"
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "issues"
    - name: "RocketMQ"
      owner: "apache"
      repo_name: "rocketmq"
      description: "Apache RocketMQ is a cloud native messaging and streaming platform, making it simple to build event-driven applications."
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "issues"
    - name: "Spring Cloud Gateway"
      owner: "spring-cloud"
      repo_name: "spring-cloud-gateway"
      description: "An API Gateway built on Spring Framework and Spring Boot providing routing and more."
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "issues"
    - name: "Spring gRPC"
      owner: "spring-projects"
      repo_name: "spring-grpc"
      description: "The Spring gRPC project provides a Spring-friendly API and abstractions for developing gRPC applications."
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "issues"
    - name: "Lettuce"
      owner: "redis"
      repo_name: "lettuce"
      description: "Advanced Java Redis client for thread-safe sync, async, and reactive usage. Supports Cluster, Sentinel, Pipelining, and codecs."
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "issues"
    - name: "Spring Cloud Commons"
      owner: "spring-cloud"
      repo_name: "spring-cloud-commons"
      description: "Common classes used in different Spring Cloud implementations"
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "issues"
    - name: "Netty Socketio"
      owner: "mrniko"
      repo_name: "netty-socketio"
      description: "Socket.IO server implemented on Java. Realtime java framework"
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "openjdk"
          logoColor: "white"
      contribution_type: "issues"
    - name: "n8n"
      owner: "n8n-io"
      description: "Fair-code workflow automation platform with native AI capabilities. Combine visual building with custom code, self-host or cloud, 400+ integrations."
      technologies:
        - name: "TypeScript"
          color: "3178C6"
          logo: "typescript"
          logoColor: "white"
      contribution_type: "issues"
    - name: "shardingsphere"
      owner: "apache"
      description: "Empowering Data Intelligence with Distributed SQL for Sharding, Scalability, and Security Across All Databases."
      technologies:
        - name: "Java"
          color: "ED8B00"
          logo: "java"
          logoColor: "white"
      contribution_type: "issues"

# GitHub Stats section configuration
github_stats:
  title: "📊 GitHub Stats"
  username: "NeatGuyCoding"
  stats:
    - type: "top-langs"
      url: "https://github-readme-stats.vercel.app/api/top-langs/"
      params:
        username: "NeatGuyCoding"
        layout: "compact"
        theme: "tokyonight"
        hide_border: "true"
      alt: "Top Languages"
      height: "170"
    - type: "streak"
      url: "https://github-readme-streak-stats.herokuapp.com/"
      params:
        user: "NeatGuyCoding"
        theme: "tokyonight"
        hide_border: "true"
      alt: "GitHub Streak"

# GitHub Trophies section configuration
github_trophies:
  title: "🏆 GitHub Trophies"
  username: "NeatGuyCoding"
  url: "https://github-profile-trophy.vercel.app/"
  params:
    username: "NeatGuyCoding"
    theme: "nord"
    column: "7"
    no_frame: "true"
  alt: "GitHub Trophies"

# Footer section configuration
footer:
  separator: "---"
  message: "Happy coding!"
  emoji: "😊"
